In [1]:
import numpy

str = '國民黨7日開中常會，談國民黨主席是否要提早交接，但未果。即將退位的國民黨主席洪秀柱允諾，下周會定案，但她在會後向媒體表示，她不知道她會不會提前請辭，但是她不會默默地走，一定要讓大家知道。中常會結束後，媒體詢問洪秀柱，若吳敦義堅持8月20日召開全代會再交接該怎麼辦，她語氣堅定地說，「他不提前交接，我就提前走」，她還透露國民黨團總召廖國棟，「天天要我滾」。至於下周是否會提前請辭，她不置可否，但是她表示，她不會默默地走，一定會讓大家知道。國民黨主席5月20日已完成改選，黨主席當選人吳敦義陣營與黨主席洪秀柱陣營為了是否提前交接及中央委員提名權、中央委員與中常委選舉是否延到8月20日全代會後等議題，爭執不休。國民黨中常委李德維等26名中常委在7日中常會提案，依黨章規定，將7月8日中央委員選舉、7月29日中常委選舉延到全代會之後舉行，避免違法爭議，進而影響選舉效力。洪秀柱親自主持會議迎戰。'

print(str.count('國民黨'))




6


In [6]:
import requests
import json
from bs4 import BeautifulSoup
import queue
import threading
import time
import datetime
import jieba
import jieba.analyse
from urllib.parse import quote

#jieba.load_userdict('userdict.txt')

str = "迎合度100%！超高級「20歲出租女友」美乳好迷人！看她忘情的扭腰畫面太刺激了… 文 / 深夜大主廚 在台灣，我們經常在網路上看到一些什麼出租女友、一日情人伴遊等廣"

seg_list = jieba.cut_for_search(str)
tags = jieba.analyse.extract_tags(str, 10)
print("|".join(seg_list))
print(",".join(tags))

迎合|度|100|%|！|超高|級|「|20|歲|出租|女友|」|美乳|好|迷人|！|看|她|忘情|的|扭腰|畫面|太|刺激|了|…| |文| |/| |深夜|大主廚| |在|台灣|，|我們|經常在網|路上|看到|一些|什麼|出租|女友|、|一日|情人|伴遊|等廣
女友,出租,100,20,美乳,畫面,大主廚,台灣,我們,經常在網


In [3]:
import requests
import json
from bs4 import BeautifulSoup
import queue
import threading
import time
import datetime
import jieba
import jieba.analyse
from urllib.parse import quote

from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine
from scipy.spatial import distance
import numpy as np

#jieba.load_userdict('userdict.txt')

def StrDistance(str1,str2,tagCnt):    
    tags1 = jieba.analyse.extract_tags(str1, 10)   
    tags2 = jieba.analyse.extract_tags(str2, 10)

    mtags = tags1 + list(set(tags2) - set(tags1))

    dictionary1 = dict(zip(mtags, [str1.count(x) for x in mtags]))
    dictionary2 = dict(zip(mtags, [str2.count(x) for x in mtags]))

    print(dictionary1)
    print(dictionary2)
    
    d = 1 - distance.cosine(np.array([v for k,v in dictionary1.items()],dtype = object),
                           np.array([v for k,v in dictionary2.items()],dtype = object))    
    return d

s1 = "狂！TAE成人展「粉紅泡泡浴」最猛畫面曝光！大尺度「挑逗影片」沒有極限…文 / 深夜大主廚 昨天在TAE活動現場的「粉紅泡泡浴」成人表演，引起了現場轟動！這"
s2 = "好色喔！TAE成人展「暗黑直播女帝」自己脫了！開場讓粉絲「嚐甜頭」畫面好害羞…文 / 深夜大主廚 經過連續三天的「2017 TAE成人博覽會」，主廚深深的體會到Julia、"

print(StrDistance(s1,s2,10))

{'泡泡浴': 2, 'TAE': 2, '粉紅': 2, '現場': 2, '成人': 2, '最猛': 1, '畫面': 1, '沒有': 1, '極限': 1, '大主廚': 1, '經過': 0, '粉絲': 0, '連續': 0, '開場': 0, '2017': 0, '女帝': 0}
{'泡泡浴': 0, 'TAE': 2, '粉紅': 0, '現場': 0, '成人': 2, '最猛': 0, '畫面': 1, '沒有': 0, '極限': 0, '大主廚': 1, '經過': 1, '粉絲': 1, '連續': 1, '開場': 1, '2017': 1, '女帝': 1}
0.5


In [10]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
nbrs = NearestNeighbors(n_neighbors=3, algorithm='ball_tree').fit(X)
distances, indices = nbrs.kneighbors(X)
print(indices ) 
print(distances)
print(nbrs.kneighbors_graph(X).toarray())

[[0 1 2]
 [1 0 2]
 [2 1 0]
 [3 4 5]
 [4 3 5]
 [5 4 3]]
[[ 0.          1.          2.23606798]
 [ 0.          1.          1.41421356]
 [ 0.          1.41421356  2.23606798]
 [ 0.          1.          2.23606798]
 [ 0.          1.          1.41421356]
 [ 0.          1.41421356  2.23606798]]
[[ 1.  1.  1.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  1.]
 [ 0.  0.  0.  1.  1.  1.]
 [ 0.  0.  0.  1.  1.  1.]]


In [9]:
import random
import numpy as np
from sklearn import neighbors

x1 = np.random.normal(50, 6, 200)
y1 = np.random.normal(5, 0.5, 200)

x2 = np.random.normal(30,6,200)
y2 = np.random.normal(4,0.5,200)

x3 = np.random.normal(45,6,200)
y3 = np.random.normal(2.5, 0.5, 200)

x_val = np.concatenate((x1,x2,x3))
y_val = np.concatenate((y1,y2,y3))

x_diff = max(x_val)-min(x_val)
y_diff = max(y_val)-min(y_val)

x_normalized = [x/(x_diff) for x in x_val]
y_normalized = [y/(y_diff) for y in y_val]
xy_normalized = zip(x_normalized,y_normalized)

print(dict(xy_normalized))

labels = [1]*200+[2]*200+[3]*200

clf = neighbors.KNeighborsClassifier(30)

?clf.fit(xy_normalized, labels)

#nearests = clf.kneighbors([(50/x_diff, 5/y_diff),(30/x_diff, 3/y_diff)], 10, False)
#nearests

{0.95152461221578843: 0.99245439336991648, 0.85375406287000111: 0.8672214150058617, 0.81894177446639138: 0.92321472095784318, 0.97023694739255162: 0.92747403275014961, 0.75611940400390432: 0.78972251279952987, 0.91337497115434163: 0.78562653501063728, 0.82805456161480762: 0.98976473315465796, 0.99396082064266666: 1.038700883468225, 0.81184729762066832: 0.89156092765962458, 0.93814669943247109: 0.95561510174516651, 0.92506458069537034: 0.91431868611618994, 0.92058708606985029: 0.96291131643541505, 0.76535910060334245: 0.88511603839157693, 0.8933055325197764: 1.0033086546828267, 0.9202857342594849: 0.85215491572340807, 0.84512185397859729: 0.74718183950051442, 0.92561772662344666: 1.217176261759074, 0.98496787779291417: 0.89039727407541536, 0.88200668458344311: 0.96796519105403911, 0.74381898721183948: 1.1180855766231463, 0.90821169237883315: 0.9911172303436977, 0.71188337571440397: 1.0996727959603756, 0.72288378135926368: 1.0815146197312859, 0.83349397716329932: 0.86361209938960282, 1.1

In [3]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine
from scipy.spatial import distance
import numpy as np

A = np.array([[1,23,2,5,6,2,2,6,2],[12,4,5,5],[1,2,4],[1],[2],[2]], dtype=object )
B = np.array([[1,23,2,5,6,2,2,6,2],[12,4,5,5],[1,2,4],[1],[2],[2]], dtype=object )

Aflat = np.hstack( A )
Bflat = np.hstack( B )

dist = distance.cosine( Aflat, Bflat )
print(dist)


print(distance.cosine(np.array([1,2,3,4,5,6],dtype = object),
                       np.array([1,2,3,4,5,6],dtype = object)))

1.11022302463e-16
0.0


In [67]:
from sklearn import metrics
from sklearn import svm
import random
import numpy as np

from sklearn.svm import SVC

# fit a SVM model to the data

size = 5
x1 = np.random.normal(1, 6, size)
x2 = np.random.normal(100, 6, size)

x_val = np.concatenate((x1,x2))


x_val = [np.random.normal(1, 6, size)] * 5
x_val1 = [np.random.normal(100, 6, size)] * 5

x_val = np.concatenate((x_val,x_val1))
print(x_val)

y_val = ['類別1'] * size + ['類別2'] * size

clf = svm.SVC(decision_function_shape='ovo')
clf.fit(x_val, y_val) 
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

predictX = np.random.normal(1, 6, size)
predictX = [100] * size
print('predictX',predictX)
print('predict result:',clf.predict(predictX))

print(metrics.classification_report(y_val, predicted))


[[  -6.91850838    2.84800453    1.24254175   -5.23056944    3.80596305]
 [  -6.91850838    2.84800453    1.24254175   -5.23056944    3.80596305]
 [  -6.91850838    2.84800453    1.24254175   -5.23056944    3.80596305]
 [  -6.91850838    2.84800453    1.24254175   -5.23056944    3.80596305]
 [  -6.91850838    2.84800453    1.24254175   -5.23056944    3.80596305]
 [  94.39895422   96.89373003  108.15437007  101.0373811    99.17597179]
 [  94.39895422   96.89373003  108.15437007  101.0373811    99.17597179]
 [  94.39895422   96.89373003  108.15437007  101.0373811    99.17597179]
 [  94.39895422   96.89373003  108.15437007  101.0373811    99.17597179]
 [  94.39895422   96.89373003  108.15437007  101.0373811    99.17597179]]
predictX [100, 100, 100, 100, 100]
predict result: ['類別2']


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


NameError: name 'predicted' is not defined

In [30]:
from sklearn import svm
X = [[0], [10], [20], [30]]
Y = [0, 1, 2, 3]
clf = svm.SVC(decision_function_shape='ovo')
clf.fit(X, Y) 
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

dec = clf.decision_function([[1]])
print(dec.shape[1]) # 4 classes: 4*3/2 = 6

clf.decision_function_shape = "ovr"
dec = clf.decision_function([[1]])
print(dec.shape[1]) # 4 classes

print(clf.predict([[20.]]))

6
4
[2]
